const express = require('express');
const cors = require('cors');
const path = require('path');
const { google } = require('googleapis');

// AWS S3 client for uploading styled transcript documents
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');

const S3_BUCKET = process.env.SESSION_DOCS_BUCKET || 'talendro-coaching-sessions';
const S3_REGION = process.env.AWS_REGION || 'us-east-2';

const s3Client = new S3Client({ region: S3_REGION });
const app = express();
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.static(path.join(__dirname, 'public')));

// ============================================
// STRIPE CONFIGURATION
// ============================================

const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;
let stripe = null;
if (STRIPE_SECRET_KEY) {
  stripe = require('stripe')(STRIPE_SECRET_KEY);
  console.log('Stripe API initialized');
} else {
  console.warn('Stripe secret key not configured - session resolution disabled');
}

// Product name to session type mapping
const PRODUCT_TO_SESSION_TYPE = {
  'Talendro™ Interview Coach - Quick Prep': 'quick_prep',
  'Talendro™ Interview Coach - Full Mock': 'full_mock',
  'Talendro™ Interview Coach - Premium Audio': 'audio_mock',
  'Talendro™ Interview Coach Pro': 'pro'
};

// ============================================
// GOOGLE SHEETS & DOCS CONFIGURATION
// ============================================

// Credentials loaded from environment variable
const GOOGLE_CREDENTIALS = JSON.parse(process.env.GOOGLE_CREDENTIALS || '{}');
const SPREADSHEET_ID = process.env.GOOGLE_SHEET_ID || '1nLXvn83ziFGpMNgBfbHE0rKCZe5PkxGHzXwGtAnKvrs';
const TRANSCRIPT_FOLDER_ID = '0AI6UfXTCoTc3Uk9PVA';
const SHEET_NAME = 'Sheet1';

// Column mapping - includes Doc URL columns
const COLUMNS = {
  EMAIL: 'C',
  QUICK_PREP_REMAINING: 'W',
  FULL_MOCK_REMAINING: 'Z',
  AUDIO_MOCK_REMAINING: 'AC',
  IS_PRO: 'AD',
  QUICK_PREP_TRANSCRIPT: 'AF',
  QUICK_PREP_GENERATED_AT: 'AG',
  FULL_MOCK_TRANSCRIPT: 'AH',
  FULL_MOCK_STARTED_AT: 'AI',
  FULL_MOCK_STATUS: 'AJ',
  AUDIO_MOCK_TRANSCRIPT: 'AK',
  AUDIO_MOCK_STARTED_AT: 'AL',
  AUDIO_MOCK_STATUS: 'AM',
  QUICK_PREP_DOC_URL: 'AN',
  FULL_MOCK_DOC_URL: 'AO',
  AUDIO_MOCK_DOC_URL: 'AP'
};

// Initialize Google APIs (Sheets AND Docs AND Drive)
let sheets = null;
let docs = null;
let drive = null;

if (GOOGLE_CREDENTIALS.client_email) {
  const auth = new google.auth.GoogleAuth({
    credentials: GOOGLE_CREDENTIALS,
    scopes: [
      'https://www.googleapis.com/auth/spreadsheets',
      'https://www.googleapis.com/auth/documents',
      'https://www.googleapis.com/auth/drive.file'
    ]
  });
  sheets = google.sheets({ version: 'v4', auth });
  docs = google.docs({ version: 'v1', auth });
  drive = google.drive({ version: 'v3', auth });
  console.log('Google Sheets, Docs, and Drive APIs initialized');
} else {
  console.warn('Google credentials not configured - session validation disabled');
}

// ============================================
// GOOGLE DOCS HELPER FUNCTIONS
// ============================================

/**
 * Create a Google Doc with the transcript and return the URL
 */
async function createTranscriptDoc(email, sessionType, transcript) {
  if (!docs || !drive) {
    console.warn('Google Docs not configured - skipping doc creation');
    return null;
  }
  
  try {
    // Format session type for display
    const sessionTypeLabels = {
      'quick_prep': 'Quick Prep',
      'full_mock': 'Full Mock Interview',
      'audio_mock': 'Audio Mock Interview'
    };
    const sessionLabel = sessionTypeLabels[sessionType] || sessionType;
    
    // Create timestamp
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
    const timeStr = now.toLocaleTimeString('en-US', { 
      hour: '2-digit', 
      minute: '2-digit' 
    });
    
    // Create the document title
    const docTitle = `Talendro Interview Coach - ${sessionLabel} - ${email} - ${dateStr}`;
    
    // Create a new Google Doc using Drive API (in the Shared Drive)
    const createResponse = await drive.files.create({
      requestBody: {
        name: docTitle,
        mimeType: 'application/vnd.google-apps.document',
        parents: [TRANSCRIPT_FOLDER_ID]
      },
      fields: 'id',
      supportsAllDrives: true
    });
    
    const documentId = createResponse.data.id;
    console.log(`Created Google Doc: ${documentId}`);
    
    // Build the document content
    const headerText = `TALENDRO™ INTERVIEW COACH\n${sessionLabel} Results\n\n`;
    const metaText = `Email: ${email}\nDate: ${dateStr} at ${timeStr}\nSession Type: ${sessionLabel}\n\n${'─'.repeat(50)}\n\n`;
    const footerText = `\n\n${'─'.repeat(50)}\n\nGenerated by Talendro™ Interview Coach\nwww.talendro.com\n`;
    
    const fullContent = headerText + metaText + transcript + footerText;
    
    // Insert content into the document
    await docs.documents.batchUpdate({
      documentId: documentId,
      requestBody: {
        requests: [
          {
            insertText: {
              location: { index: 1 },
              text: fullContent
            }
          },
          // Format the header (first line)
          {
            updateParagraphStyle: {
              range: { startIndex: 1, endIndex: headerText.indexOf('\n') + 1 },
              paragraphStyle: {
                namedStyleType: 'HEADING_1',
                alignment: 'CENTER'
              },
              fields: 'namedStyleType,alignment'
            }
          }
        ]
      }
    });
    
    // Make the document viewable by anyone with the link
    await drive.permissions.create({
      fileId: documentId,
      requestBody: {
        role: 'reader',
        type: 'anyone'
      },
      supportsAllDrives: true
    });
    
    // Get the document URL
    const docUrl = `https://docs.google.com/document/d/${documentId}/view`;
    console.log(`Google Doc created and shared: ${docUrl}`);
    
    return docUrl;
    
  } catch (error) {
    console.error('Error creating Google Doc:', error);
    // Don't throw - we don't want to fail the whole request if doc creation fails
    return null;
  }
}

// ============================================
// GOOGLE SHEETS HELPER FUNCTIONS
// ============================================

async function findUserRow(email) {
  if (!sheets) return null;
  
  try {
    const response = await sheets.spreadsheets.values.get({
      spreadsheetId: SPREADSHEET_ID,
      range: `${SHEET_NAME}!C:C`
    });
    
    const rows = response.data.values || [];
    for (let i = 0; i < rows.length; i++) {
      if (rows[i][0] && rows[i][0].toLowerCase() === email.toLowerCase()) {
        return i + 1;
      }
    }
    return null;
  } catch (error) {
    console.error('Error finding user row:', error);
    throw error;
  }
}

async function getUserData(email) {
  if (!sheets) return null;
  
  try {
    const rowNum = await findUserRow(email);
    if (!rowNum) {
      return null;
    }
    
    const response = await sheets.spreadsheets.values.get({
      spreadsheetId: SPREADSHEET_ID,
      range: `${SHEET_NAME}!A${rowNum}:AP${rowNum}`
    });
    
    const row = response.data.values ? response.data.values[0] : [];
    
    // DEBUG LOGGING
    console.log('=== DEBUG getUserData ===');
    console.log('Row number:', rowNum);
    console.log('Row length:', row.length);
    console.log('Row[22] (Quick Prep Remaining):', row[22]);
    console.log('Row[25] (Full Mock Remaining):', row[25]);
    console.log('Row[35] (Full Mock Status):', row[35]);
    console.log('=========================');
    
    return {
      rowNum,
      email: row[2] || '',
      quickPrepRemaining: parseInt(row[22]) || 0,
      fullMockRemaining: parseInt(row[25]) || 0,
      audioMockRemaining: parseInt(row[28]) || 0,
      isPro: row[29]?.toLowerCase() === 'true' || row[29]?.toLowerCase() === 'yes',
      quickPrepTranscript: row[31] || '',
      quickPrepGeneratedAt: row[32] || '',
      fullMockTranscript: row[33] || '',
      fullMockStartedAt: row[34] || '',
      fullMockStatus: row[35] || '',
      audioMockTranscript: row[36] || '',
      audioMockStartedAt: row[37] || '',
      audioMockStatus: row[38] || '',
      quickPrepDocUrl: row[39] || '',
      fullMockDocUrl: row[40] || '',
      audioMockDocUrl: row[41] || ''
    };
  } catch (error) {
    console.error('Error getting user data:', error);
    throw error;
  }
}

async function updateMultipleCells(rowNum, updates) {
  if (!sheets) return;
  
  try {
    const data = updates.map(({ column, value }) => ({
      range: `${SHEET_NAME}!${column}${rowNum}`,
      values: [[value]]
    }));
    
    await sheets.spreadsheets.values.batchUpdate({
      spreadsheetId: SPREADSHEET_ID,
      resource: {
        valueInputOption: 'RAW',
        data
      }
    });
  } catch (error) {
    console.error('Error updating multiple cells:', error);
    throw error;
  }
}

// ============================================
// SESSION VALIDATION LOGIC
// ============================================

function isWithin48Hours(dateString) {
  if (!dateString) return false;
  const startTime = new Date(dateString);
  const now = new Date();
  const hoursDiff = (now - startTime) / (1000 * 60 * 60);
  return hoursDiff <= 48;
}

async function validateSession(email, sessionType) {
  const userData = await getUserData(email);
  
  if (!userData) {
    return {
      allowed: false,
      reason: 'User not found. Please complete your purchase first.',
      showTranscript: false
    };
  }
  
  switch (sessionType) {
    case 'quick_prep':
      if (userData.quickPrepTranscript) {
        return {
          allowed: false,
          reason: 'completed',
          showTranscript: true,
          transcript: userData.quickPrepTranscript,
          generatedAt: userData.quickPrepGeneratedAt,
          docUrl: userData.quickPrepDocUrl
        };
      }
      if (userData.quickPrepRemaining <= 0 && !userData.isPro) {
        return {
          allowed: false,
          reason: 'No Quick Prep sessions remaining. Please purchase another session.',
          showTranscript: false
        };
      }
      return { allowed: true };
      
    case 'full_mock':
      if (userData.fullMockTranscript && userData.fullMockStatus === 'completed') {
        return {
          allowed: false,
          reason: 'completed',
          showTranscript: true,
          transcript: userData.fullMockTranscript,
          generatedAt: userData.fullMockStartedAt,
          docUrl: userData.fullMockDocUrl
        };
      }
      if (userData.fullMockStatus === 'in_progress' && isWithin48Hours(userData.fullMockStartedAt)) {
        return { 
          allowed: true, 
          reconnection: true,
          message: 'Reconnecting to your in-progress session...'
        };
      }
      if (userData.fullMockStatus === 'in_progress' && !isWithin48Hours(userData.fullMockStartedAt)) {
        return {
          allowed: false,
          reason: 'Your session expired after 48 hours. Please purchase a new session.',
          showTranscript: false
        };
      }
      if (userData.fullMockRemaining <= 0 && !userData.isPro) {
        return {
          allowed: false,
          reason: 'No Full Mock sessions remaining. Please purchase another session.',
          showTranscript: false
        };
      }
      return { allowed: true };
      
    case 'audio_mock':
      if (userData.audioMockTranscript && userData.audioMockStatus === 'completed') {
        return {
          allowed: false,
          reason: 'completed',
          showTranscript: true,
          transcript: userData.audioMockTranscript,
          generatedAt: userData.audioMockStartedAt,
          docUrl: userData.audioMockDocUrl
        };
      }
      if (userData.audioMockStatus === 'in_progress' && isWithin48Hours(userData.audioMockStartedAt)) {
        return { 
          allowed: true, 
          reconnection: true,
          message: 'Reconnecting to your in-progress session...'
        };
      }
      if (userData.audioMockStatus === 'in_progress' && !isWithin48Hours(userData.audioMockStartedAt)) {
        return {
          allowed: false,
          reason: 'Your session expired after 48 hours. Please purchase a new session.',
          showTranscript: false
        };
      }
      if (userData.audioMockRemaining <= 0 && !userData.isPro) {
        return {
          allowed: false,
          reason: 'No Audio Mock sessions remaining. Please purchase another session.',
          showTranscript: false
        };
      }
      return { allowed: true };
      
    case 'pro':
      if (!userData.isPro) {
        return {
          allowed: false,
          reason: 'Pro subscription required. Please upgrade to Pro.',
          showTranscript: false
        };
      }
      return { allowed: true };
      
    default:
      return {
        allowed: false,
        reason: 'Invalid session type.',
        showTranscript: false
      };
  }
}

// ============================================
// API ENDPOINTS
// ============================================

// Resolve Stripe checkout session to get customer email and product
app.get('/api/resolve-stripe-session', async (req, res) => {
  try {
    const { session_id } = req.query;
    
    if (!session_id) {
      return res.status(400).json({ error: 'Session ID required' });
    }
    
    if (!stripe) {
      console.error('Stripe not configured');
      return res.status(500).json({ error: 'Stripe not configured' });
    }
    
    // Retrieve the checkout session from Stripe
    const session = await stripe.checkout.sessions.retrieve(session_id, {
      expand: ['line_items', 'line_items.data.price.product']
    });
    
    if (!session) {
      return res.status(404).json({ error: 'Session not found' });
    }
    
    // Get customer email
    const email = session.customer_details?.email || session.customer_email;
    
    if (!email) {
      return res.status(400).json({ error: 'No email found in session' });
    }
    
    // Get product name and map to session type
    let sessionType = 'quick_prep'; // default
    
    if (session.line_items?.data?.length > 0) {
      const productName = session.line_items.data[0].price?.product?.name || 
                          session.line_items.data[0].description;
      
      // Try exact match first
      if (PRODUCT_TO_SESSION_TYPE[productName]) {
        sessionType = PRODUCT_TO_SESSION_TYPE[productName];
      } else {
        // Try partial matching
        const productLower = productName?.toLowerCase() || '';
        if (productLower.includes('full mock')) {
          sessionType = 'full_mock';
        } else if (productLower.includes('audio') || productLower.includes('premium')) {
          sessionType = 'audio_mock';
        } else if (productLower.includes('pro')) {
          sessionType = 'pro';
        } else if (productLower.includes('quick prep')) {
          sessionType = 'quick_prep';
        }
      }
    }
    
    console.log(`Resolved Stripe session: email=${email}, sessionType=${sessionType}`);
    
    res.json({ 
      success: true, 
      email, 
      sessionType,
      redirectUrl: `/?session_type=${sessionType}&email=${encodeURIComponent(email)}`
    });
    
  } catch (error) {
    console.error('Error resolving Stripe session:', error);
    res.status(500).json({ error: 'Failed to resolve session', details: error.message });
  }
});

app.post('/api/check-session', async (req, res) => {
  try {
    const { email, sessionType } = req.body;
    
    if (!email || !sessionType) {
      return res.status(400).json({ error: 'Email and session type required' });
    }
    
    // If Google Sheets not configured, allow access
    if (!sheets) {
      return res.json({ allowed: true });
    }
    
    const validation = await validateSession(email, sessionType);
    res.json(validation);
  } catch (error) {
    console.error('Error checking session:', error);
    res.status(500).json({ error: 'Failed to validate session' });
  }
});

app.post('/api/start-session', async (req, res) => {
  try {
    const { email, sessionType } = req.body;
    
    if (!email || !sessionType) {
      return res.status(400).json({ error: 'Email and session type required' });
    }
    
    if (!sheets) {
      return res.json({ success: true, startedAt: new Date().toISOString() });
    }
    
    const userData = await getUserData(email);
    if (!userData) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    const now = new Date().toISOString();
    
    if (sessionType === 'full_mock') {
      if (userData.fullMockStatus !== 'in_progress') {
        await updateMultipleCells(userData.rowNum, [
          { column: COLUMNS.FULL_MOCK_STARTED_AT, value: now },
          { column: COLUMNS.FULL_MOCK_STATUS, value: 'in_progress' }
        ]);
      }
    } else if (sessionType === 'audio_mock') {
      if (userData.audioMockStatus !== 'in_progress') {
        await updateMultipleCells(userData.rowNum, [
          { column: COLUMNS.AUDIO_MOCK_STARTED_AT, value: now },
          { column: COLUMNS.AUDIO_MOCK_STATUS, value: 'in_progress' }
        ]);
      }
    }
    
    res.json({ success: true, startedAt: now });
  } catch (error) {
    console.error('Error starting session:', error);
    res.status(500).json({ error: 'Failed to start session' });
  }
});

// ============================================
// SAVE TRANSCRIPT - CREATE TALENDRO-STYLED HTML IN S3
// ============================================

app.post('/api/save-transcript', async (req, res) => {
  try {
    const { email, sessionType, transcript } = req.body;

    if (!email || !sessionType || !transcript) {
      return res.status(400).json({ error: 'Email, session type, and transcript required' });
    }

    if (!sheets) {
      return res.json({ success: true, savedAt: new Date().toISOString() });
    }

    const userData = await getUserData(email);
    if (!userData) {
      return res.status(404).json({ error: 'User not found' });
    }

    const now = new Date().toISOString();

    // ---- Build Talendro-styled HTML ----
    const sessionTypeLabels = {
      quick_prep: 'Quick Prep Session',
      full_mock: 'Full Mock Interview',
      audio_mock: 'Audio Mock Interview'
    };
    const sessionLabel = sessionTypeLabels[sessionType] || sessionType;

    const escapeHtml = (str) =>
      String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');

    const safeTranscript = escapeHtml(transcript);

    const safeEmail = email.replace(/[^a-zA-Z0-9.@_-]/g, '');
    const timestampSlug = now.replace(/[:.]/g, '-');
    const s3Key = `sessions/users/${safeEmail}/${timestampSlug}-${sessionType}.html`;

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${sessionLabel} – Talendro Interview Coach</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body {
      margin: 0;
      padding: 32px;
      background: #020617;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: #e5e7eb;
    }
    .card {
      max-width: 880px;
      margin: 0 auto;
      background: #020617;
      border-radius: 18px;
      padding: 32px 32px 40px;
      border: 1px solid #1f2937;
      box-shadow: 0 18px 40px rgba(15, 23, 42, 0.7);
    }
    .logo {
      font-weight: 700;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      font-size: 12px;
      color: #a4f400;
    }
    .logo span {
      color: #2f6df6;
    }
    .pill {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 4px 10px;
      border-radius: 999px;
      background: rgba(15, 118, 110, 0.15);
      color: #6ee7b7;
      font-size: 11px;
      margin-top: 8px;
    }
    h1 {
      font-size: 24px;
      margin: 20px 0 6px;
    }
    h2 {
      font-size: 16px;
      margin: 22px 0 10px;
      color: #e5e7eb;
    }
    .meta {
      font-size: 12px;
      color: #9ca3af;
      margin-bottom: 12px;
    }
    .section {
      margin-top: 20px;
      padding-top: 16px;
      border-top: 1px solid #111827;
    }
    pre {
      white-space: pre-wrap;
      word-wrap: break-word;
      font-family: inherit;
      font-size: 14px;
      line-height: 1.6;
      color: #e5e7eb;
    }
    .footer {
      margin-top: 28px;
      font-size: 12px;
      color: #6b7280;
    }
    a {
      color: #93c5fd;
      text-decoration: none;
    }
  </style>
</head>
<body>
  <div class="card">
    <div class="logo"><span>Talendro™</span> Interview Coach</div>
    <div class="pill">Precision Matches. Faster Results.</div>

    <h1>${sessionLabel} Coaching Notes</h1>

    <div class="meta">
      Sent to: ${escapeHtml(email)}<br/>
      Session completed: ${escapeHtml(
        new Date(now).toLocaleString('en-US', { timeZone: 'UTC' })
      )} UTC
    </div>

    <div class="section">
      <h2>Coaching Transcript</h2>
      <pre>${safeTranscript}</pre>
    </div>

    <div class="footer">
      This read-only document captures your Talendro™ Interview Coach session.
    </div>
  </div>
</body>
</html>`;

    // ---- Upload HTML to S3 ----
    let docUrl = null;
    try {
      await s3Client.send(
        new PutObjectCommand({
          Bucket: S3_BUCKET,
          Key: s3Key,
          Body: html,
          ContentType: 'text/html; charset=utf-8'
        })
      );

      // Public URL (bucket policy already allows s3:GetObject)
      docUrl = `https://${S3_BUCKET}.s3.${S3_REGION}.amazonaws.com/${s3Key}`;
    } catch (err) {
      console.error('Error uploading transcript HTML to S3:', err);
    }

    // ---- Update Google Sheet (no transcript text) ----
    switch (sessionType) {
      case 'quick_prep':
        await updateMultipleCells(userData.rowNum, [
          { column: COLUMNS.QUICK_PREP_GENERATED_AT, value: now },
          { column: COLUMNS.QUICK_PREP_DOC_URL, value: docUrl || '' }
        ]);
        break;

      case 'full_mock':
        await updateMultipleCells(userData.rowNum, [
          { column: COLUMNS.FULL_MOCK_STATUS, value: 'completed' },
          { column: COLUMNS.FULL_MOCK_DOC_URL, value: docUrl || '' }
        ]);
        break;

      case 'audio_mock':
        await updateMultipleCells(userData.rowNum, [
          { column: COLUMNS.AUDIO_MOCK_STATUS, value: 'completed' },
          { column: COLUMNS.AUDIO_MOCK_DOC_URL, value: docUrl || '' }
        ]);
        break;

      default:
        console.warn('Unknown sessionType in save-transcript:', sessionType);
        break;
    }

    res.json({
      success: true,
      savedAt: now,
      docUrl: docUrl
    });
  } catch (error) {
    console.error('Error saving transcript:', error);
    res.status(500).json({ error: 'Failed to save transcript' });
  }
});

// ============================================
// GENERATE POLISHED INTERVIEW DEBRIEF (Full Mock / Audio Mock)
// ============================================

app.post('/api/generate-debrief', async (req, res) => {
  try {
    const { conversationHistory, documents, sessionType } = req.body;

    if (!conversationHistory || conversationHistory.length === 0) {
      return res.status(400).json({ error: 'Conversation history required' });
    }

    const anthropicApiKey = process.env.ANTHROPIC_API_KEY;
    if (!anthropicApiKey) {
      return res.status(500).json({ error: 'Anthropic API key not configured' });
    }

    // Format conversation for the prompt
    const conversationText = conversationHistory
      .map((msg) => {
        const role = msg.role === 'user' ? 'CANDIDATE' : 'INTERVIEWER';
        return `${role}: ${msg.content}`;
      })
      .join('\n\n');

    // Session label
    const sessionTypeLabel =
      sessionType === 'audio_mock'
        ? 'Premium Audio Mock Interview'
        : 'Full Mock Interview';

    const interviewerMessages = conversationHistory.filter(
      (msg) => msg.role === 'assistant'
    );
    const questionCount = Math.max(interviewerMessages.length, 5);

    const resume = documents?.resume || 'Not provided';
    const jobDescription = documents?.jobDescription || 'Not provided';
    const companyUrl = documents?.companyUrl || 'Not provided';

    const debriefPrompt = `
You are Talendro™ Interview Coach, a world-class executive interview coach.

A candidate has just completed a ${sessionTypeLabel}.
You are creating a professional Interview Debrief Document for them.

Use the information below:

RESUME:
${resume}

JOB DESCRIPTION:
${jobDescription}

COMPANY WEBSITE:
${companyUrl}

MOCK INTERVIEW TRANSCRIPT:
${conversationText}

There were approximately ${questionCount} interview questions.

Create a beautifully formatted debrief document with:

1. **Overall Assessment**
   - 2–4 sentences summarizing how the candidate performed.

2. **Key Strengths (3–5 bullet points)**
   - Be specific and tie to their answers and behaviors.

3. **Top Improvement Areas (3–5 bullet points)**
   - Focus on what will actually move the needle in real interviews.

4. **Question-by-Question Breakdown**
   For each major question you can infer from the transcript:
   - The question (or best reconstruction of it)
   - What the candidate did well
   - What could be improved
   - A suggested upgraded / ideal answer.

5. **Before Your Interview**
   - A short checklist (4–7 items) of what this candidate should do in the days/hours before their interview.

6. **During Your Interview**
   - A short checklist (4–7 items) of what to remember in the room / on the call.

7. **Final Thoughts**
   - 2–3 sentences of encouragement and motivation.
   - Be direct, supportive, and confidence-building.

Style:
- Write for a senior professional / executive-level candidate.
- Be concise but specific.
- Use headings, numbered lists, and bullets so it reads like a premium coaching report.
`;

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': anthropicApiKey,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json'
      },
      body: JSON.stringify({
        model: 'claude-3-5-sonnet-latest',
        max_tokens: 6000,
        messages: [{ role: 'user', content: debriefPrompt }]
      })
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      console.error('Anthropic API error (debrief):', error);
      throw new Error(`Anthropic API error: ${error.error?.message || 'Unknown error'}`);
    }

    const data = await response.json();
    const debriefText = data.content?.[0]?.text || '';

    return res.json({
      success: true,
      debrief: debriefText
    });
  } catch (error) {
    console.error('Error generating debrief:', error);
    return res.status(500).json({ error: 'Failed to generate debrief' });
  }
});

// ============================================
// CHAT ENDPOINT (AI calls via Anthropic)
// ============================================

app.post('/api/chat', async (req, res) => {
  try {
    const {
      message,
      sessionType,
      documents,
      customerEmail,
      conversationHistory
    } = req.body;

    const anthropicApiKey = process.env.ANTHROPIC_API_KEY;

    if (!anthropicApiKey) {
      return res.status(500).json({ error: 'Anthropic API key not configured' });
    }

    const systemPrompt =
      (typeof SYSTEM_PROMPTS !== 'undefined' && SYSTEM_PROMPTS[sessionType]) ||
      (typeof SYSTEM_PROMPTS !== 'undefined' && SYSTEM_PROMPTS.quick_prep) ||
      'You are Talendro Interview Coach. Be concise, practical, and specific.';

    // Build context from documents (only added once)
    let context = '';
    if (documents) {
      if (documents.resume) {
        context += `\n\nCANDIDATE RESUME:\n${documents.resume}`;
      }
      if (documents.jobDescription) {
        context += `\n\nJOB DESCRIPTION:\n${documents.jobDescription}`;
      }
      if (documents.companyUrl) {
        context += `\n\nCOMPANY WEBSITE URL: ${documents.companyUrl}`;
      }
    }

    let messages = [];

    if (conversationHistory && conversationHistory.length > 0) {
      messages = conversationHistory.map((msg, index) => {
        if (index === 0 && msg.role === 'user' && context) {
          return {
            role: msg.role,
            content: `${msg.content}\n\n---\nCONTEXT:${context}`
          };
        }
        return { role: msg.role, content: msg.content };
      });

      messages.push({ role: 'user', content: message });
    } else {
      messages = [
        {
          role: 'user',
          content: context ? `${message}\n\n---\nCONTEXT:${context}` : message
        }
      ];
    }

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': anthropicApiKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-3-5-sonnet-latest',
        max_tokens: 4096,
        system: systemPrompt,
        messages
      })
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      console.error('Anthropic API error (chat):', error);
      throw new Error(
        `Anthropic API error: ${error.error?.message || response.statusText}`
      );
    }

    const data = await response.json();
    const assistantMessage =
      data.content && data.content[0] && data.content[0].text
        ? data.content[0].text
        : '';

    return res.json({ message: assistantMessage });
  } catch (error) {
    console.error('Chat error:', error);
    return res.status(500).json({ error: 'Failed to get AI response' });
  }
});

// ============================================
// WEBHOOK FOR ZAPIER (session completion)
// ============================================

app.post('/api/webhook/session-complete', async (req, res) => {
  try {
    const { email, sessionType, transcript, feedback, docUrl } = req.body;

    const zapierWebhookUrl = 'https://hooks.zapier.com/hooks/catch/9843127/uko6xa9/';

    await fetch(zapierWebhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email,
        sessionType,
        transcript,
        feedback,
        docUrl,
        completedAt: new Date().toISOString()
      })
    });

    res.json({ success: true });
  } catch (error) {
    console.error('Webhook error (session-complete):', error);
    res.status(500).json({ error: 'Webhook failed' });
  }
});

// ============================================
// SERVE FRONTEND
// ============================================

app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// ============================================
// START SERVER
// ============================================

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Interview Coach server running on port ${PORT}`);
});
